### ISSUE TITLE
Risc-V 64-bit binaries

### ISSUE THREAD

**Issue by tinspin** [rednblackgames/gdx-miniaudio#10]
Any plans for this? I know audio barely works at all on all the Risc-V boards we have so far but still...

**Comment by fgnm** [comment]
`gdx-jnigen` does supports risc-v as target, so in the long run this is absolutely doable and planned. Currently, I don't have any testing device and don't know even if MiniAuido should have a special support on its side, anyway when I'll update to jnigen v3 I'll try to add the risc-v target and see what happens

**Comment by tinspin** [comment]
If you could compile a 0.5 risc-v 64-bit binary I can test it now, I digged out my Vision Five 2!

**Comment by fgnm** [comment]
@tinspin you could check the latest SNAPSHOT which includes RISCV x64 target... Let me know if it works

**Comment by tinspin** [comment]
Thx, the binary loads but audio is buggy. It's across the machine so I blame risc-v debian. Let's wait for the official release... *skeleton*

**Comment by fgnm** [comment]
Choosing the backend at moment can't be made at runtime, but you've to compile from yourself and change that array: https://github.com/rednblackgames/gdx-miniaudio/blob/8ffb55e275a86cd3bce58969dcad5c8726a63bd7/src/main/java/games/rednblack/miniaudio/MiniAudio.java#L269 , it's a trick I did to disable AAudio backend, it can be surely do it batter by passing the backend list from java to C.

About the in/out audio device you've to create the MiniAudio object with `initEngine` flag to false, enumerate devices and call `MiniAudio#initEngine` by yourself with appropriate `playbackId` and `captureId` passing the `idAddress` you want. Again this is still not possible to change after creating the engine. In this part there's a huge room of improvements

**Comment by tinspin** [comment]
Ok, not bad. Is there a way to verbose what the backed selection is? That would be a good start.

**Comment by fgnm** [comment]
MiniAudio chose backend by trial and errors based on the list you provide at context initialization, so the first one that works is the one used. You can use `MiniAudio#setLogCallback` to register a java callback of miniaudio internal logs.. at beginning you should understand which backend is used.. Tbh I think I never anything then PulseAudio on Linux 🤔
