### ISSUE TITLE
Shouldn't there also be a setListenerVelocity(x, y, z)?

### ISSUE THREAD

**Issue by Hotshot5000** [rednblackgames/gdx-miniaudio#5]
I see there are setListenerPosition Direction WorldUp but MiniAudio also exposes a setListenerVelocity which isn't exposed here.
Could it be missing or am I misunderstanding something?

**Comment by fgnm** [comment]
Yes, you right, totally miss them.. I'll do ASAP, thanks for reporting

**Comment by Hotshot5000** [comment]
Created a PR here https://github.com/rednblackgames/gdx-miniaudio/pull/6

**Comment by fgnm** [comment]
Released in `v0.4` :)
